spring:
  config:
    activate:
      on-profile: prod
  mvc:
    async:
      request-timeout: ${REQUEST_TIMEOUT}
  messages:
    basename: validation

server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      charset: UTF-8

management:
  health:
    readinessState:
      enabled: true
    circuitbreakers:
      enabled: true
    livenessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - info
          - env
          - prometheus
          - readiness
          - liveness
      base-path: /metrics
    enabled-by-default: true
  endpoint:
    health:
      status:
        http-mapping:
          out-of-service: 503
          down: 503
          fatal: 503
          up: 200
      environmentVariablesHealthIndicator:
        enabled: true
      probes:
        add-additional-paths: true
        enabled: true
      show-details: always
      show-components: always
      validate-group-membership: true
      group:
        readiness:
          include:
            - environmentVariables
            - readinessState
        liveness:
          include:
            - livenessState
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

resilience4j:
  circuitbreaker:
    instances:
      switch-service:
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
        wait-duration-in-open-state: 5s
        sliding-window-size: 10

logging:
  level:
    org:
      springframework:
        boot:
          actuate:
            health:
              HealthEndpointSupport: ERROR
    root: ${LOGGING_LEVEL}

required-environment-variables:
  SERVER_PORT,
  LOGGING_LEVEL